model_name: "google/mt5-base"
output_dir: "./results"
logging_dir: "./logs"
num_train_epochs: 3
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
warmup_steps: 500
weight_decay: 0.01
learning_rate: 5e-5
save_steps: 500
evaluation_strategy: "steps"
eval_steps: 500
save_total_limit: 2
